mediafrontend/views/__init__.py
from functools import wraps
import time
import hashlib
import base64
import os
from datetime import datetime, timezone
import math
import re
import json

from flask import Blueprint, render_template, abort, request, redirect, jsonify
from flask import url_for, g, send_from_directory, make_response
import dateutil.parser

from .. import MediaFrontend
from media import MediumStatus, MediumProtection
from accounts.views import require_sign_in
from pagination_from_request import pagination_from_request
from parse_id import generate_or_parse_id

def initialize(
		config,
		accounts,
		access_log,
		engine,
		install=False,
		connection=None,
	):
	g.media = MediaFrontend(
		config,
		accounts,
		access_log,
		engine,
		install=install,
		connection=connection,
	)

	# use default medium and tags file uris if custom uris aren't specified
	if not g.media.config['medium_file_uri']:
		g.media.config['medium_file_uri'] = url_for(
			'media_static.medium_file',
			medium_filename='MEDIUM_FILENAME',
			_external=True,
		).replace('MEDIUM_FILENAME', '{}')
	if not g.media.config['summary_file_uri']:
		g.media.config['summary_file_uri'] = url_for(
			'media_static.summary_file',
			summary_filename='SUMMARY_FILENAME',
			_external=True,
		).replace('SUMMARY_FILENAME', '{}')
	protected_tags_file_uri = url_for(
			'media_static.tags_file',
			tags_filename='TAGS_FILENAME',
			_external=True,
		).replace('TAGS_FILENAME', '{}')
	g.media.config['protected_tags_file_uri'] = protected_tags_file_uri
	if not g.media.config['tags_file_uri']:
		g.media.config['tags_file_uri'] = protected_tags_file_uri

	#TODO limit maximum upload filesize by determining min of server capability and config capability
	pass

# require objects or abort
def require_medium(id):
	try:
		medium = g.media.require_medium(id)
	except ValueError as e:
		abort(404, str(e))
	else:
		return medium

media_static = Blueprint(
	'media_static',
	__name__,
	static_folder='static',
	static_url_path='/static',
)

@media_static.route('/files/<medium_filename>')
def medium_file(medium_filename):
	nonprotected_media_path = os.path.join(
		g.media.config['media_path'],
		'nonprotected',
	)
	if not os.path.exists(
			os.path.join(
				nonprotected_media_path,
				medium_filename,
			)
		):
		abort(404)
	return send_from_directory(
		nonprotected_media_path,
		medium_filename,
		conditional=True,
	)

@media_static.route('/summaries/<summary_filename>')
def summary_file(summary_filename):
	nonprotected_summary_path = os.path.join(
		g.media.config['summaries_path'],
		'nonprotected',
	)
	if not os.path.exists(
			os.path.join(
				nonprotected_summary_path,
				summary_filename,
			)
		):
		abort(404)
	return send_from_directory(
		nonprotected_summary_path,
		summary_filename,
		conditional=True,
	)

@media_static.route('/tags/<tags_filename>')
def tags_file(tags_filename):
	if not os.path.exists(
			os.path.join(
				g.media.config['tags_path'],
				tags_filename,
			)
		):
		abort(404)

	if 'signed_out.json' != tags_filename:
		if not g.media.accounts.current_user:
			abort(401)
		if (
				(
					'contributor.json' == tags_filename
					or 'semantic.json' == tags_filename
				)
				and not g.media.accounts.current_user.has_permission(
					group_names='contributor',
				)
			):
			abort(403)
		if (
				'manager.json' == tags_filename
				and not g.media.accounts.current_user.has_permission(
					group_names='manager',
				)
			):
			abort(403)

	return send_from_directory(
		g.media.config['tags_path'],
		tags_filename,
		conditional=True,
	)

media_supplemental = Blueprint(
	'media_supplemental',
	__name__,
	template_folder='templates',
)

@media_supplemental.route('/help')
def help():
	return render_template('media_help.html')

media_api = Blueprint(
	'media_api',
	__name__,
	template_folder='templates',
)

def api_access_not_allowed(medium, owner_or_manager_only=False):
	# return regular non-allowed response code
	# to not expose private or forbidden media
	if 200 != medium.current_user_response_code:
		return '', medium.current_user_response_code
	if owner_or_manager_only:
		# owner or manager only
		if (
				g.media.accounts.current_user != medium.owner_id
				and not g.media.accounts.current_user.has_permission(
					group_names='manager',
				)
			):
			return '', 403
	return False

def api_response_thumbnails(media, response_data=None):
	if not response_data:
		response_data = {'media': {}}
	for medium in media.values():
		response_data['media'][medium.id] = {
			'thumbnail': render_template(
				'medium_thumbnail.html',
				medium=medium,
				no_thumbnail_link=True,
				tiles=True,
				kwargs={},
			).replace(
				'\r',
				'',
			).replace(
				'\n',
				'',
			).replace(
				'\t',
				'',
			),
		}
	return response_data

@media_api.route('/fetch_medium/<medium_filename>')
@require_sign_in
def api_fetch_medium(medium_filename):
	protected_media_path = os.path.join(
		g.media.config['media_path'],
		'protected',
	)
	if not os.path.exists(
			os.path.join(protected_media_path, medium_filename)
		):
		return '', 404
	medium_id = medium_filename.split('.')[0]
	medium = require_medium(medium_id)
	response = api_access_not_allowed(medium)
	if response:
		return response
	return send_from_directory(
		protected_media_path,
		medium_filename,
		conditional=True,
	)

@media_api.route('/fetch_summary/<summary_filename>')
@require_sign_in
def api_fetch_summary(summary_filename):
	protected_summaries_path = os.path.join(
		g.media.config['summaries_path'],
		'protected',
	)
	if not os.path.exists(
			os.path.join(protected_summaries_path, summary_filename)
		):
		return '', 404
	medium_id = summary_filename.split('.')[0]
	medium = require_medium(medium_id)
	response = api_access_not_allowed(medium)
	if response:
		return response
	return send_from_directory(
		protected_summaries_path,
		summary_filename,
		conditional=True,
	)

@media_api.route('/tags/build', methods=['POST'])
@require_sign_in
def api_build_tag_suggestions():
	if (
			not g.media.accounts.current_user.has_permission(
				group_names='contributor',
			)
			and not g.media.accounts.current_user.has_permission(
				group_names='manager',
			)
		):
		return '', 403
	g.media.build_tag_suggestions()
	return '', 200

@media_api.route('/tags/<mode>', methods=['POST'])
@require_sign_in
def api_tags(mode):
	if mode not in ['set', 'add', 'remove']:
		return '', 400
	for field in ['medium_ids', 'tags']:
		if field not in request.form:
			return '', 400
	medium = require_medium(request.form['medium_ids'].split(',')[0])
	response = api_access_not_allowed(medium, owner_or_manager_only=True)
	tags = g.media.tag_string_to_list(request.form['tags'])
	if response:
		return response
	if 'set' == mode:
		g.media.set_tags(medium.id, tags)
	elif 'add' == mode:
		g.media.add_tags(medium.id, tags)
	elif 'remove' == mode:
		g.media.remove_tags(medium.id, tags)
	# refetch after changes
	media = g.media.search_media(filter={'ids':medium.id_bytes})
	g.media.populate_media_covers(media)
	response_data = api_response_thumbnails(media)
	r = make_response(json.dumps(response_data))
	r.mimetype = 'application/json'
	return r, 200

@media_api.route('/medium/upload', methods=['POST'])
@require_sign_in
def api_upload_medium():
	if not g.media.accounts.current_user.has_permission(
			group_names='contributor',
		):
		return '', 403
	if 'view_endpoint' not in request.form:
		return '', 400
	return upload_media(request.form['view_endpoint'], api_request=True)

@media_api.route('/medium/edit', methods=['POST'])
@require_sign_in
def api_edit_medium():
	if 'medium_ids' not in request.form:
		return '', 400
	medium = require_medium(request.form['medium_ids'].split(',')[0])
	response = api_access_not_allowed(medium, owner_or_manager_only=True)
	if response:
		return response
	errors, medium = process_edit_medium(medium)
	if errors:
		# no need to return robust errors since only thumbnail class changes
		return '', 400
	# refetch after changes
	media = g.media.search_media(filter={'ids': medium.id_bytes})
	g.media.populate_media_covers(media)
	response_data = api_response_thumbnails(media)
	r = make_response(json.dumps(response_data))
	r.mimetype = 'application/json'
	return r, 200

@media_api.route('/medium/generate_summaries', methods=['POST'])
@require_sign_in
def api_generate_medium_summaries():
	if 'medium_ids' not in request.form:
		return '', 400
	medium = require_medium(request.form['medium_ids'].split(',')[0])
	response = api_access_not_allowed(medium, owner_or_manager_only=True)
	if response:
		return response
	# catch everything here and return generic error if something goes wrong
	try:
		g.media.generate_medium_summaries(medium)
	except:
		return '', 400
	# refetch after changes
	media = g.media.search_media(filter={'ids':medium.id_bytes})
	g.media.populate_media_covers(media)
	response_data = api_response_thumbnails(media)
	r = make_response(json.dumps(response_data))
	r.mimetype = 'application/json'
	return r, 200

@media_api.route('/generate_set', methods=['POST'])
def api_generate_media_set():
	if 'medium_ids' not in request.form:
		return '', 400
	medium_ids = request.form['medium_ids'].split(',')
	if not medium_ids:
		return '', 400
	media = g.media.search_media(filter={'ids': medium_ids})
	for medium in media.values():
		response = api_access_not_allowed(medium, owner_or_manager_only=True)
		if response:
			return response
	set_tags = []
	if 'sync' not in request.form:
		new_set_tag, new_set_tag_bytes = generate_or_parse_id(None)
		set_tags = 'set:' + new_set_tag
	else:
		if not media:
			return '', 400
		for medium in media.values():
			if 'sets' in medium.semantic_tags:
				for set in medium.semantic_tags['sets']:
					if 'set:' + set not in set_tags:
						set_tags.append('set:' + set)
	g.media.remove_tags(medium_ids, set_tags)
	g.media.add_tags(medium_ids, set_tags)
	g.media.build_tag_suggestions()
	# refetch after changes
	media = g.media.search_media(filter={'ids': medium_ids})
	g.media.populate_media_covers(media)

mediafrontend/views/templates/confirm_delete_medium_original_file.html
{% extends 'layout.html' %}
{% block title %}Delete original file{% endblock %}
{% block content %}
	<div class="confirm">
		<h1>Delete original file</h1>
		<p>Deleting original files is irreversible. Are you sure?</p>
		<p>
			<a 
				href="{{ url_for(
					request.endpoint,
					medium_id=medium_id,
					tags=tags_query,
					mode='delete_original',
					confirm='1',
					**kwargs,
				) }}">
				Delete original file
			</a>
		</p>
	</div>
{% endblock %}

mediafrontend/views/templates/edit_medium_form.html
<form method="post" enctype="multipart/form-data" novalidate>
	{% set hidden_focus = False %}
	{% if 
		medium.data1 != medium.data2
		and (
			medium.data1
			or medium.data2
		) %}
		<label for="focus">Focus</label>
		<input 
			id="focus" 
			name="focus" 
			type="range" 
			min="0" 
			max="1" 
			step="0.01" 
			value="{{ fields['focus'] }}">
		<br>
	{% else %}
		{% set hidden_focus = True %}
	{% endif %}
	{% include 'medium_groups_form.html' %}
	{% include 'medium_properties_form.html' %}
	<div id="replacement">
		<legend>Replacement</legend>
		{% include 'medium_creation_form.html' %}
	</div>
	{% if hidden_focus %}
		<input type="hidden" name="focus" value="0.5">
	{% endif %}
	<input type="submit" value="Save Changes">
</form>

mediafrontend/views/templates/media_help_features.html
<table>
	<caption>Features</caption>
	<tbody>
		<tr>
			<td>Help</td>
			<td>This page</td>
		</tr>
		<tr>
			<td>Slideshow</td>
			<td>Begins a slideshow of the current search results</td>
		</tr>
		<tr>
			<td>RSS</td>
			<td>RSS feed of the current search if available</td>
		</tr>
	</tbody>
</table>

mediafrontend/views/templates/media_rich_data.html
<meta name="twitter:card" content="summary_large_image">
{% set card_image = medium.uris['fallback'][g.media.config['summary_values']['view']] %}
{% if 'image/gif' == medium.mime and 1 < medium.data4 %}
	{% set card_image = medium.uris['original'] %}
{% endif %}
<meta 
	name="twitter:image" 
	content="{{ card_image }}">
<meta 
	property="og:image" 
	content="{{ card_image }}">

{% if medium.uris['reencoded']['clip'] %}
	<meta property="og:video" content="{{ medium.uris['reencoded']['clip'] }}">
{% endif %}
{% if 'author' in medium.semantic_tags %}
	<meta property="og:author" content="{{ medium.semantic_tags['author'] }}">
{% endif %}
	
{% set title = '' %}
{% if 'title' in medium.semantic_tags %}
	{% set title = medium.semantic_tags['title'] %}
{% else %}
	{% set title = 'View media ' + medium.id %}
{% endif %}
<meta name="twitter:title" content="{{ title }}">
<meta property="og:title" content="{{ title }}">

{% set tags = [] %}
{% for tag in medium.tags %}
	{% set _ = tags.append('#' + tag) %}
{% endfor %}
{% set description = ' '.join(tags) %}
{% set description = description ~ ' - created ' ~ medium.creation_datetime.strftime('%Y-%m-%d') %}
<meta name="twitter:description" content="{{ description }}">
<meta name="og:description" content="{{ description }}">

<meta property="og:type" content="persephone:medium-view">

mediafrontend/views/templates/medium_blurb.html
{% if 'blurb' in medium.semantic_tags %}
	<div class="medium_blurb">{{ medium.semantic_tags['blurb']|safe }}</div>
{% endif %}

mediafrontend/views/templates/medium_creation_form.html
<div id="creation">
	<span class="form_file">
		<label for="file_upload">File by Upload</label>
		<input 
			id="file_upload" 
			name="file_upload" 
			type="file" 
			data-maximum-upload-filesize="{{ g.media.config['maximum_upload_filesize'] }}" 
			data-file-too-large="File Too Large" required>
		<span 
			class="file_selection" 
			data-file-selected="File selected" 
			data-file-not-selected="No file selected"></span>
	</span>
	<br>
	<label for="file_uri">File by URI</label>
	<input 
		id="file_uri" 
		name="file_uri" 
		type="text" 
		value="{{ fields['file_uri'] }}" 
		placeholder="Enter URI of remote file">
</div>

mediafrontend/views/templates/medium_groups_form.html
{% if g.media.config['requirable_groups'] %}
	{% from 'permissions.jinja' import group_display %}
	<div id="groups">
		<legend>Required Groups</legend>
		{% for group in g.media.config['requirable_groups'] %}
			{% if group in g.media.accounts.available_groups %}
				{% set checked = '' %}
				{% if ('groups' in fields) and (group in fields['groups']) %}
					{% set checked = ' checked' %}
				{% endif %}
				<input id="group_{{ group }}" name="group_{{ group }}" type="checkbox"{{ checked }}>
				<label for="group_{{ group }}">{{ group_display(group) }}</label>
				<br>
			{% endif %}
		{% endfor %}
		<input type="hidden" name="groups" value="1">
	</div>
{% endif %}

mediafrontend/views/templates/medium_info.html
<div class="medium_info">
	{% include 'medium_like_block.html' %}
	{% from 'media.jinja' import filesize %}
	<span class="size">{{ filesize(medium.size) }}</span>
	<span 
		class="creation_date" 
		data-timestamp="{{ medium.creation_time }}">
		{{ medium.creation_datetime.strftime('%Y-%m-%dT%H:%M:%S.%f%z') }}
	</span>
	{% if 0 < medium.data1 and 0 < medium.data2 %}
		<span class="dimensions">
			<span class="width">{{ medium.data1 }}</span>x<span class="height">{{ medium.data2 }}</span>
		</span>
	{% endif %}
	{% if 1 < medium.data4 %}
		<span class="frames">{{ medium.data4 }} frames</span>
	{% endif %}
	{% if 0 < medium.data5 %}
		<span class="duration">{{ medium.data5 }} ms</span>
	{% endif %}
	{% if 0 < medium.data6 %}
		<span class="bitrate">{{ medium.data6 }} kbps</span>
	{% endif %}
</div>

mediafrontend/views/templates/medium_rgb.html
{% if medium.rgb %} style="--checker_h: rgba({{ medium.rgb['r'] }}, {{ medium.rgb['g'] }}, {{ medium.rgb['b'] }}, 0.15);"{% endif %}

mediafrontend/views/templates/medium_semantic_tag_block.html
{% if medium.semantic_tags %}
	<table class="medium_semantic_tag_info">
		<tbody>
			{% for tag, display in {
				'prev': 'Previous in sequence',
				'next': 'Next in sequence',
				'inferior of': 'Inferior of',
				'superior of': 'Superior of',
			}.items() %}
				{% if tag in medium.semantic_tags %}
					<tr>
						<td>{{ display }}</td>
						<td>
							<a href="{{ url_for(
									request.endpoint,
									medium_id=medium.semantic_tags[tag],
									**kwargs,
								) }}">
								{{ medium.semantic_tags[tag] }}
							</a>
						</td>
					</tr>
				{% endif %}
			{% endfor %}
			{% for namespace, display in {
				'mirror': 'Mirror',
				'url': 'URL',
				'source url': 'Source',
				'creator url': 'Creator',
				'character url': 'Character',
			}.items() %}
				{% if namespace in medium.semantic_tags %}
					{% for tag in medium.semantic_tags[namespace] %}
						<tr>
							<td>{{ display }}</td>
							<td>
								<a href="{{ tag	}}" >
									{{ tag }}
								</a>
							</td>
						</tr>
					{% endfor %}
				{% endif %}
			{% endfor %}
			{# {% if 'mirror' in medium.semantic_tags %}
				<tr>
					<td>Mirror</td>
					<td>
						<a href="{{ medium.semantic_tags['mirror'] }}">
							{{ medium.semantic_tags['mirror'] }}
						</a>
					</td>
				</tr>
			{% endif %} #}
		</tbody>
	</table>
{% endif %}

mediafrontend/views/templates/tags_this_page.html
{% if tags_this_page %}
	<div id="tags_this_page">
		<h2>Tags this page</h2>
		<div>
			{% for tag in tags_this_page %}
				{% set clear_query = re.sub(
					'#+',
					'#',
					re.sub(
						'(^|#)\-?'
							+ tag.replace(
								'\\',
								'\\\\'
							).replace(
								'(',
								'\(',
							).replace(
								')',
								'\)',
							)
							+ '(#|$)',
						'#',
						tags_query + '#'
					)
				).replace('\\\\', '\\') %}
				{% if '#' == clear_query[0] %}
					{% set clear_query = clear_query[1:] %}
				{% endif %}
				<span 
					class="tag" 
					data-tag="{{ tag }}">
					<a 
						href="{{ url_for(
							request.endpoint,
							tags=tag,
							**kwargs,
						) }}" 
						title="Search this tag">{{ tag }}</a>
					<a 
						class="action add" 
						href="{{ url_for(
							request.endpoint,
							tags=clear_query + tag,
							**kwargs,
						) }}" 
						title="Add this tag to current search">+</a>
					<a 
						class="action remove" 
						href="{{ url_for(
							request.endpoint,
							tags=clear_query + '-' + tag,
							**kwargs,
						) }}" 
						title="Remove this tag from current search">-</a>
				</span>
			{% endfor %}
		</div>
	</div>
{% endif %}

mediafrontend/views/templates/upload_media.html
{% extends 'layout.html' %}
{% block title %}Upload{% endblock %}
{% block content %}
	<h1>Upload</h1>
	{% include 'medium_form_errors.html' %}
	<form 
		method="post" 
		enctype="multipart/form-data" 
		data-action-upload="{{ url_for('media_api.api_upload_medium') }}" 
		data-action-build-tag-suggestions="{{ url_for('media_api.api_build_tag_suggestions') }}" 
		data-advanced="Advanced options" novalidate>
		{% include 'medium_groups_form.html' %}
		{% include 'medium_properties_form.html' %}
		{% include 'upload_media_tagging_form.html' %}
		{% include 'medium_creation_form.html' %}
		<input type="hidden" name="view_endpoint" value="{{ view_endpoint }}">
		<input type="submit" value="Create">
	</form>
{% endblock %}

mediafrontend/views/templates/upload_media_tagging_form.html
<div id="tagging">
	<legend>Tagging</legend>
	<input 
		id="author_tag" 
		name="author_tag" 
		type="checkbox"{% if fields['author_tag'] %} checked{% endif %}>
	<label for="author_tag">Creator Tag</label>
	<br>
	<input 
		id="filename_tag" 
		name="filename_tag" 
		type="checkbox"{% if fields['filename_tag'] %} checked{% endif %}>
	<label for="filename_tag">Filename Tag</label>
	<br>
	<label for="tags">Additional Tags</label>
	<input id="tags" name="tags" type="text" value="{{ fields['tags'] }}">
</div>

mediafrontend/views/templates/view_medium_tags.html
<div class="medium_tags" data-visible-tags="{{ visible_tags }}">
	<div class="inner_tags">
		{% for tag in medium.tags %}
			<span 
				class="tag{% if tag in clutter_tags %} clutter_tag{% endif %}" 
				data-tag="{{ tag }}" 
				title="Search for this tag">
				<a href="{{ url_for(request.endpoint, tags=tag, **kwargs) }}">#{{ tag }}</a>
			</span>
		{% endfor %}
	</div>
</div>